[workspace]
resolver = "2"
members = [
    "mantra",
    "langs/mantra-lang-tracing",
    "langs/rust/mantra-rust-procm",
    "langs/rust/mantra-rust-macros",
    "langs/rust/mantra-rust-trace",
    "langs/rust/examples/*",
]

[workspace.dependencies]
proc-macro2 = "1.0.81"
regex = "1.10.4"
tree-sitter = "0.20.10"
tree-sitter-rust = "0.20.4"
cc = "1.0.90"

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/mhatzl/mantra"
license = "MIT"
