[package]
name = "mantra"
version = "0.1.0"
edition = "2021"
description = "Tool to trace requirements down to implementation and tests."
repository = "https://github.com/mhatzl/mantra"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logid = "0.12.1"
thiserror = "1.0.47"
clap = "4.3.24"
regex = "1.9.3"
