[package]
name = "mantra-rust-trace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mantra-lang-tracing = { path = "../../mantra-lang-tracing" }
tree-sitter = "0.20.10"
tree-sitter-rust = "0.20.4"

[build-dependencies]
cc = "1.0.90"

