[package]
name = "mantra-rust-trace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mantra-lang-tracing = { path = "../../mantra-lang-tracing" }
tree-sitter.workspace = true
tree-sitter-rust.workspace = true

[build-dependencies]
cc.workspace = true

