[package]
name = "mantra-extract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mantra-db = { path = "../db" }
regex = "1.9.3"
ignore = "0.4.20"
clap.workspace = true
