[env]
# Note: Switch `SQLX_OFFLINE` to `true` if editor seems to be getting slow.
SQLX_OFFLINE = "false"
# Note: Keep in sync with setting in justfile; Defining it here is needed for sqlx queries to work without offline support
DATABASE_URL = "sqlite://mantra.db?mode=rwc"
