# Note: set "SQLX_OFFLINE_DIR" to absolute path to the workspace ".sqlx" folder for `cargo publish` to work
# see: https://github.com/launchbadge/sqlx/issues/3644
[env]
DATABASE_URL = "sqlite://mantra.db"
SQLX_OFFLINE = "true"