[package]
name = "mantra"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Tool to trace requirements down to implementation and tests."
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logid = "0.12.2"
thiserror = "1.0.47"
clap = { version = "4.4.1", features = ["derive"] }
regex = "1.9.3"
walkdir = "2.3.3"
