[package]
name = "fn-cover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.3"
mantra-rust-macros = { path = "../../mantra-rust-macros", features = ["stdout", "log"] }
