[package]
name = "mantra-lang-tracing"
description = "Contains functionality needed to collect requirement traces from code or plain text files for the `mantra` framework."
version.workspace = true
edition.workspace = true
repository.workspace = true 
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mantra-schema = { path = "../../schema", version = "0" }
serde.workspace = true
path-slash = "0.2"
proc-macro2 = { workspace = true, optional = true }
regex = { workspace = true, optional = true }
tree-sitter = { workspace = true, optional = true }

[build-dependencies]
cc = { version = "1.0.90", optional = true }

[dev-dependencies]
mantra-rust-macros = { path = "../rust/mantra-rust-macros", version = "0" }

[features]
default = ["collect"]
collect = ["extract", "dep:tree-sitter", "dep:cc"]
extract = ["dep:proc-macro2", "dep:regex"]
