[package]
name = "mantra-lang-tracing"
version.workspace = true
edition.workspace = true
repository.workspace = true 
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2.workspace = true
regex.workspace = true
tree-sitter.workspace = true
tree-sitter-rust.workspace = true 

[build-dependencies]
cc.workspace = true

[dev-dependencies]
#mantra-rust-macros = { path = "../rust/mantra-rust-macros", version = "0" }
