[package]
name = "mantra-lang-tracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.81"
regex = "1.10.4"
tree-sitter = "0.20.10"
tree-sitter-rust = "0.20.4"

[build-dependencies]
cc = "1.0.90"

[dev-dependencies]
mantra-rust-macros = { path = "../rust/mantra-rust-macros" }
