name: mantra
on: 
  workflow_run:
    workflows: [docker]
    types:
        - completed
  workflow_dispatch:

permissions:
    contents: write

jobs:
    # Synchronizes references between project and wiki.
    #            
    # [req:sync.ci]
    mantra-sync:
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

        runs-on: ubuntu-latest
        container:
            image: manuelhatzl/mantra:main

        env:
            # see: https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
            # Note: We only care about `ref_name`, because this workflow should only be triggered on `push`.
            BRANCH_NAME: ${{ github.ref_name }} 

        steps:
            - uses: actions/checkout@v3
              with:
                repository: 'mhatzl/mantra-wiki'
                path: './wiki'
                # PAT with 'workflow' permission required in case wiki-links in workflow files get updated
                token: ${{ secrets.MANTRA_TOKEN }}

            - uses: actions/checkout@v3
              with:
                path: './proj_folder'

            - name: sync-references
              run: mantra sync --branch-name=$BRANCH_NAME --branch-link=https://github.com/mhatzl/mantra/tree/$BRANCH_NAME ./wiki/5-Requirements ./proj_folder

            - name: job-date
              id: job-date
              run: |
                echo "date=$(date -u +'%Y-%m-%d_%H:%M UTC')" >> $GITHUB_OUTPUT

            - name: update-sidebar
              run: |
                sed -i -r "s/\*\*Last update:\*\*.+/\*\*Last update:\*\* ${{ steps.job-date.outputs.date }}/" ./wiki/_Sidebar.md
                sed -i -r "s/\*\*Branch:\*\*.+/\*\*Branch:\*\* $BRANCH_NAME/" ./wiki/_Sidebar.md
                sed -i -r "s/\*\*Commit:\*\*.+/\*\*Commit:\*\* ${{ github.sha }}/" ./wiki/_Sidebar.md
                cat ./wiki/_Sidebar.md

            - name: push-changes
              working-directory: ./wiki
              # In case nothing changed
              continue-on-error: true
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git status
                git add .
                git commit -m "chore: sync references between wiki and project"
                git push
