name: mantra-pr
on:
    pull_request:
    workflow_dispatch:

permissions:
    issues: write

jobs:
    mantra-pr:
        runs-on: ubuntu-latest
        container:
            image: manuelhatzl/mantra:main

        env:
            # see: https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
            # Note: We only care about `head_ref`, because this workflow should only be triggered on `pull_requests`.
            # `ref_name` is used for workflow_dispatch.
            BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

        steps:
            - uses: actions/checkout@v3
              with:
                repository: 'mhatzl/mantra-wiki'
                path: './req_folder'
                sparse-checkout: 5-Requirements

            - uses: actions/checkout@v3
              with:
                path: './proj_folder'

            - name: check
              id: check
              # '2>&1' forwards stderr to stdout, so error logs get included in output.
              # Uses ' ' (U+2002) isntead of regular space for output, because GitHub output cannot handle regular spaces
              # see: https://stackoverflow.com/questions/59191913/how-do-i-get-the-output-of-a-specific-step-in-github-actions
              run: |
                mantra check --branch-name=$BRANCH_NAME ./req_folder ./proj_folder 2>&1 > check_overview.md
                output="$(cat check_overview.md)"
                output="${output//$'\n'/\\n}"
                output="${output// / }" 
                cat check_overview.md
                echo "check-overview=$output" >> $GITHUB_OUTPUT

            - name: summary
              # The *newline* replacement is needed to get nice formatting in the summary
              run: |
                summary="$(echo '${{ steps.check.outputs.check-overview }}')"
                summary="${summary//\\n/
                }"
                echo "$summary" >> $GITHUB_STEP_SUMMARY

            - name: comment
              if: ${{ github.event_name == 'pull_request' }}
              uses: actions/github-script@v6
              with:
                script: |
                    github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: '${{ steps.check.outputs.check-overview }}'
                    })
