name: mantra-link
on: workflow_dispatch

jobs:
    mantra-link:
        runs-on: ubuntu-latest
        container:
            image: manuelhatzl/mantra:latest
            volumes:
                - ./req_folder:/req_folder
                - ./proj_folder:/proj_folder

        steps:
            - uses: actions/checkout@v3
              with:
                repository: 'mhatzl/mantra-wiki'
                path: './req_folder'
                sparse-checkout: 5-Requirements

            - uses: actions/checkout@v3
              with:
                path: './proj_folder'

            - name: update-links
              run: mantra link --wiki-url-prefix=https://github.com/mhatzl/mantra/wiki/ /req_folder /proj_folder

            - name: push-changes
              working-directory: ./proj_folder
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add .
                git commit -m "chore: update wiki-links in project repository"
                git push
