name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # [req:qa.pipeline.1_style](https://github.com/mhatzl/mantra/wiki/5-REQ-qa.pipeline.1_style#qapipeline1_style-ensure-consistent-formatting)
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run cargo fmt
      run: cargo fmt -- --check

  # [req:qa.pipeline.2_lint](https://github.com/mhatzl/mantra/wiki/5-REQ-qa.pipeline.2_lint#qapipeline2_lint-ensure-good-coding-standard)
  lint:
    name: Run Linter (clippy)
    runs-on: ubuntu-latest
    # [req:qa.sustain](https://github.com/mhatzl/mantra/wiki/5-REQ-qa.sustain#qasustain-consider-sustainability-during-design-and-development)
    needs: format
    
    steps:
    - uses: actions/checkout@v2
    - name: Run linter
      run: cargo clippy -- -D warnings

  # [req:qa.pipeline.3_build](https://github.com/mhatzl/mantra/wiki/5-REQ-qa.pipeline.3_build#qapipeline3_build-ensure-evident-builds)
  build:
    name: Run Build
    runs-on: ubuntu-latest
    # [req:qa.sustain](https://github.com/mhatzl/mantra/wiki/5-REQ-qa.sustain#qasustain-consider-sustainability-during-design-and-development)
    needs: lint

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

  # [req:qa.pipeline.4_tests](https://github.com/mhatzl/mantra/wiki/5-REQ-qa.pipeline.4_tests#qapipeline4_tests-ensure-tests-still-pass)
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    # [req:qa.sustain](https://github.com/mhatzl/mantra/wiki/5-REQ-qa.sustain#qasustain-consider-sustainability-during-design-and-development)
    needs: build
    
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
